dist: trusty
services:
- docker
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.arquillian"
  - "$HOME/.rvm/"
  - bundler
before_script:
- git config --global http.postBuffer 157286400
script:
- if [[ $TRAVIS_COMMIT_MESSAGE != *"prepare release"* ]]; then mvn clean generate-resources
  ; fi ;
- if [[ $TRAVIS_COMMIT_MESSAGE == *"prepare release"* ]]; then mvn clean generate-resources
  -Prelease -Prelease ; fi ;
after_success:
- mvn scm-publish:publish-scm
env:
  global:
  - secure: jWbaz6YKMLRZH5muQae/L3sU79dnGFhDWZ/byeUOlj1+l6PAvZ+X9wYib9nVYAtlOhjChH2yDekxWYBxO0+LbjnXMvzIDgedlD4ar4smvIQT5bnjxfzRdyvPo29DQnZGd7GI4JBFTR2q9aJ/rgeTrL4kL4J+M+8ojtEO9cYuX0c8wuMBAUIKCQORjCGSvaVeluaqv4thYX3n0mU+5+8Jpg1Na+nxGAF+Y33ssFOZd3jY7HrnrRNzmIdapJqe5GByGQhRoQJXNvD1cHOJdjN4WaEsfVrTUxzeLa1BJEbG/to30Wg6B4Mwf2JzhfBjm+AXjOQk3FUi97CS7bwreLqvjKgp7k4uTr54L47KBNn7EUgZqTkruYIx1ZHoiNxh22Yno12tsNnvE75prEWT6beGAcaw10WS722d3JMWNuX91RxunY3HhQhXunUhjFGBHPsiWLN6JaG9iPDqasrMFZAkqZuz+wKojy0zlK/csnEtb8eUgpurIv239SfXqnKPmHdTAX/DzehYm2z4w2zOGqXbm1A5DyEShrwumoI+dbCdl46MqI0RVryU+Wr/asbS38pFSHUVM7xAs/DzW1l/Cn3Tqna/H43ip20C0Ay3tMPaQpTXmkoJW/GW2NuHY011fcbARtfpweOSquqwsTGjWztSm/L4bf8GoBk0cim6QymykdU=
